[package]
name = "uplog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.14"}
serde = { version = "1.0.126", features = ["derive"] }
serde_cbor = "0.11.1"